### ISSUE TITLE
Defender scans virus

### ISSUE THREAD

**Issue by Attackvector1000** [sebaxakerhtc/installrefindonwindows#1]
hello, i need help btw, your script is great! i cant download the zip because windows claims for it to have a virus.
can anyone help me?
![defenderoutput](https://user-images.githubusercontent.com/66911222/131916686-8304fe3a-fe91-43d6-88a5-7518ad71cdaa.PNG)

**Comment by sebaxakerhtc** [comment]
> 

It's because my script mount and work with efi partition, I think.
Or because of bat to exe.
If you don't tust it - just paste commands one by one.
